runtime: nodejs20
env: standard

entrypoint: node backend/server.js

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  target_cpu_utilization: 0.85

handlers:
  - url: /.*
    script: auto
    secure: always